# Загрузка результатов

In [4]:
import pandas as pd
names = ['log_reg_no_fe.csv', 'rf_no_fe.csv', 'logreg_results.csv',
         'rf_results.csv']
# df = pd.read_csv
def get_df(name):
    df = pd.read_csv(name)
    df['method'] = name.split('.')[0]
    return df.sample(10)
dfs = [get_df(name) for name in names] + [parquet]

In [5]:
combined_metrics = pd.concat(dfs, axis=0)
combined_metrics

,Unnamed: 0,number,value,datetime_start,datetime_complete,duration,params_model__C,params_model__max_iter,params_model__solver,state,...,params_model__class_weight,params_model__max_depth,params_model__max_features,params_model__min_samples_leaf,params_model__min_samples_split,params_model__n_estimators,timestamp,params,score,duration_sec
5,5.0,5.0,0.488229,2026-06-16 18:10:00.657888,2026-06-16 18:10:03.320154,0 days 00:00:02.662266,1.599636,3800.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,0.488347,2026-06-16 18:09:50.192872,2026-06-16 18:09:52.614523,0 days 00:00:02.421651,3.712670,8500.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,39.0,39.0,0.489951,2026-06-16 18:12:00.312951,2026-06-16 18:12:06.431055,0 days 00:00:06.118104,9.994455,7500.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30.0,30.0,0.489714,2026-06-16 18:11:14.344477,2026-06-16 18:11:19.882889,0 days 00:00:05.538412,3.235284,5400.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,34.0,34.0,0.490202,2026-06-16 18:11:34.897735,2026-06-16 18:11:39.880572,0 days 00:00:04.982837,4.416334,5900.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17.0,17.0,0.488293,2026-06-16 18:10:33.390485,2026-06-16 18:10:35.642219,0 days 00:00:02.251734,1.434882,4400.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21.0,21.0,0.488208,2026-06-16 18:10:44.734326,2026-06-16 18:10:46.953703,0 days 00:00:02.219377,0.675542,1000.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,45.0,45.0,0.489875,2026-06-16 18:12:34.457863,2026-06-16 18:12:39.073737,0 days 00:00:04.615874,6.330968,8100.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15.0,15.0,0.488813,2026-06-16 18:10:27.551160,2026-06-16 18:10:30.022895,0 days 00:00:02.471735,0.960639,1000.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6.0,6.0,0.488263,2026-06-16 18:10:03.322779,2026-06-16 18:10:05.990335,0 days 00:00:02.667556,1.908079,7200.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0.0,0.0,0.558026,2026-06-16 18:19:15.468813,2026-06-16 18:27:20.218511,0 days 00:08:04.749698,NaN,NaN,NaN,COMPLETE,...,balanced,3.0,log2,11.0,7.0,470.0,NaN,NaN,NaN,NaN
15,15.0,15.0,0.605705,2026-06-16 18:37:09.249977,2026-06-16 18:37:46.863920,0 days 00:00:37.613943,NaN,NaN,NaN,COMPLETE,...,balanced,8.0,NaN,14.0,11.0,50.0,NaN,NaN,NaN,NaN
16,16.0,16.0,0.605660,2026-06-16 18:37:34.751397,2026-06-16 18:39:28.540537,0 days 00:01:53.789140,NaN,NaN,NaN,COMPLETE,...,balanced,8.0,NaN,2.0,11.0,230.0,NaN,NaN,NaN,NaN
10,10.0,10.0,0.627081,2026-06-16 18:29:59.400369,2026-06-16 18:34:12.675348,0 days 00:04:13.274979,NaN,NaN,NaN,COMPLETE,...,balanced,13.0,NaN,16.0,8.0,410.0,NaN,NaN,NaN,NaN
13,13.0,13.0,0.626528,2026-06-16 18:34:12.689466,2026-06-16 18:37:09.241213,0 days 00:02:56.551747,NaN,NaN,NaN,COMPLETE,...,balanced,13.0,NaN,16.0,2.0,170.0,NaN,NaN,NaN,NaN
3,3.0,3.0,0.072269,2026-06-16 18:27:20.241617,2026-06-16 18:28:10.650209,0 days 00:00:50.408592,NaN,NaN,NaN,COMPLETE,...,NaN,3.0,sqrt,18.0,2.0,350.0,NaN,NaN,NaN,NaN
4,4.0,4.0,0.625685,2026-06-16 18:28:02.738416,2026-06-16 18:29:07.415896,0 days 00:01:04.677480,NaN,NaN,NaN,COMPLETE,...,balanced,18.0,log2,7.0,6.0,350.0,NaN,NaN,NaN,NaN
18,18.0,18.0,0.636876,2026-06-16 18:39:28.547093,2026-06-16 18:46:14.727739,0 days 00:06:46.180646,NaN,NaN,NaN,COMPLETE,...,balanced,18.0,NaN,11.0,15.0,470.0,NaN,NaN,NaN,NaN
7,7.0,7.0,0.591859,2026-06-16 18:29:07.425858,2026-06-16 18:29:32.445197,0 days 00:00:25.019339,NaN,NaN,NaN,COMPLETE,...,balanced,8.0,sqrt,7.0,18.0,110.0,NaN,NaN,NaN,NaN
9,9.0,9.0,0.619953,2026-06-16 18:29:32.449712,2026-06-16 18:30:23.253562,0 days 00:00:50.803850,NaN,NaN,NaN,COMPLETE,...,balanced,18.0,log2,14.0,19.0,350.0,NaN,NaN,NaN,NaN
9,9.0,9.0,0.536947,2026-06-16 16:41:47.851584,2026-06-16 16:41:51.512779,0 days 00:00:03.661195,8.394940,6400.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,48.0,48.0,0.536893,2026-06-16 16:44:28.938429,2026-06-16 16:44:32.954430,0 days 00:00:04.016001,4.375700,8900.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16.0,16.0,0.536893,2026-06-16 16:42:14.331759,2026-06-16 16:42:17.941481,0 days 00:00:03.609722,4.447436,8400.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,2.0,0.536476,2026-06-16 16:41:06.326050,2026-06-16 16:41:14.022954,0 days 00:00:07.696904,7.145512,5100.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,49.0,49.0,0.536463,2026-06-16 16:44:32.956634,2026-06-16 16:44:36.594604,0 days 00:00:03.637970,2.920021,6600.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,33.0,33.0,0.537080,2026-06-16 16:43:19.736795,2026-06-16 16:43:23.383374,0 days 00:00:03.646579,7.355252,6100.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11.0,11.0,0.536942,2026-06-16 16:41:55.152017,2026-06-16 16:41:59.293853,0 days 00:00:04.141836,9.738696,7100.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,47.0,47.0,0.535890,2026-06-16 16:44:21.934482,2026-06-16 16:44:28.934840,0 days 00:00:07.000358,1.519166,9900.0,lbfgs,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29.0,29.0,0.536506,2026-06-16 16:43:03.796328,2026-06-16 16:43:07.682665,0 days 00:00:03.886337,3.267642,7400.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,30.0,30.0,0.537080,2026-06-16 16:43:07.685676,2026-06-16 16:43:12.039715,0 days 00:00:04.354039,7.312534,7700.0,newton-cholesky,COMPLETE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,2.0,0.184243,2026-06-16 17:19:14.940210,2026-06-16 17:19:33.135490,0 days 00:00:18.195280,NaN,NaN,NaN,COMPLETE,...,NaN,8.0,log2,15.0,8.0,230.0,NaN,NaN,NaN,NaN
7,7.0,7.0,0.570127,2026-06-16 17:21:51.720555,2026-06-16 17:22:11.045667,0 days 00:00:19.325112,NaN,NaN,NaN,COMPLETE,...,NaN,18.0,log2,11.0,4.0,110.0,NaN,NaN,NaN,NaN
14,14.0,14.0,0.654581,2026-06-16 17:32:10.990408,2026-06-16 17:34:44.228712,0 days 00:02:33.238304,NaN,NaN,NaN,COMPLETE,...,balanced,13.0,sqrt,20.0,20.0,410.0,NaN,NaN,NaN,NaN
17,17.0,17.0,0.657181,2026-06-16 17:35:38.678315,2026-06-16 17:37:51.325019,0 days 00:02:12.646704,NaN,NaN,NaN,COMPLETE,...,balanced,13.0,sqrt,17.0,17.0,410.0,NaN,NaN,NaN,NaN
11,11.0,11.0,0.676951,2026-06-16 17:22:20.079781,2026-06-16 17:29:39.738007,0 days 00:07:19.658226,NaN,NaN,NaN,COMPLETE,...,balanced,18.0,sqrt,20.0,20.0,470.0,NaN,NaN,NaN,NaN
6,6.0,6.0,0.594632,2026-06-16 17:21:20.056243,2026-06-16 17:21:57.402849,0 days 00:00:37.346606,NaN,NaN,NaN,COMPLETE,...,balanced,3.0,sqrt,8.0,16.0,170.0,NaN,NaN,NaN,NaN
18,18.0,18.0,0.677863,2026-06-16 17:36:59.478174,2026-06-16 17:39:12.185703,0 days 00:02:12.707529,NaN,NaN,NaN,COMPLETE,...,balanced,18.0,sqrt,17.0,15.0,350.0,NaN,NaN,NaN,NaN
4,4.0,4.0,0.625569,2026-06-16 17:19:33.147065,2026-06-16 17:20:57.623632,0 days 00:01:24.476567,NaN,NaN,NaN,COMPLETE,...,balanced,8.0,sqrt,5.0,6.0,170.0,NaN,NaN,NaN,NaN
8,8.0,8.0,0.065343,2026-06-16 17:21:57.409176,2026-06-16 17:22:17.065009,0 days 00:00:19.655833,NaN,NaN,NaN,COMPLETE,...,NaN,3.0,log2,11.0,14.0,290.0,NaN,NaN,NaN,NaN
5,5.0,5.0,0.195351,2026-06-16 17:20:57.629435,2026-06-16 17:21:51.713061,0 days 00:00:54.083626,NaN,NaN,NaN,COMPLETE,...,NaN,8.0,log2,4.0,8.0,470.0,NaN,NaN,NaN,NaN
0,NaN,NaN,0.706776,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2026-06-15T18:35:35.296278,"{""iterations"": 800, ""depth"": 5, ""learning_rate...",0.706776,65.638634

# Графики

In [7]:
import plotly.graph_objects as go
import plotly.express as px
import pandas as pd
import plotly.io as pio

custom_style = go.layout.Template(pio.templates["plotly_white"])

custom_style.layout.update(
    paper_bgcolor="#fcfbfa",
    plot_bgcolor="#f7f5f0",
    font=dict(
        family="Segoe UI, Arial, sans-serif",
        size=13,
        color="#3d4047"
    ),

    margin=dict(t=80, b=60, l=60, r=40),
    title=dict(
        font=dict(size=22, color="#1c212d", weight="bold"),
        pad=dict(b=10)
    )
)

custom_style.layout.colorway = [
    "#deb887",
    "#e28743",
    "#6b8e6b",
    "#e06d75",
    "#205072"
]

axis_config = dict(
    gridcolor="#eae6df",
    zerolinecolor="#d3cbd0",
    tickcolor="#c8becc",
    ticklen=6,
    linecolor="#eae6df",
    showgrid=True,
    ticks="outside",
    title=dict(font=dict(weight="bold", color="#1c212d")),
    tickfont=dict(
        size=12,
        color="#545861",
        family="Arial, sans-serif"
    )
)

custom_style.layout.xaxis = go.layout.XAxis(axis_config)
custom_style.layout.yaxis = go.layout.YAxis(axis_config)

custom_style.layout.legend = dict(
    bgcolor="rgba(252, 251, 250, 0.9)",
    bordercolor="#eae6df",
    borderwidth=1,
    orientation="h",
    yanchor="bottom", y=1.02,
    xanchor="right", x=1
)


pio.templates["summer_minimal"] = custom_style
pio.templates.default = "summer_minimal"

In [8]:

# Сортируем данные по времени старта
df_sorted = combined_metrics.sort_values('datetime_start').reset_index(drop=True)

# Добавляем колонку-порядковый номер (ось X)
df_sorted['order'] = df_sorted.index + 1  # чтобы начиналось с 1

# Строим точечный график без линий
fig = px.scatter(
    df_sorted,
    x='order',
    y='value',
    color='method',
    title='F1-score Кросс-Валидация на 5 фолдах',
    labels={
        'order': 'Номер эксперимента',
        'value': 'F1',
        'method': 'Метод'
    }
)

fig.update_traces(marker=dict(size=18))

fig.show()

In [9]:
parquet = pd.read_parquet('experiment_results_catboost.parquet')
parquet['value'] = parquet['score']
parquet

,timestamp,method,params,score,duration_sec,value
0,2026-06-15T18:35:35.296278,catboost,"{""iterations"": 800, ""depth"": 5, ""learning_rate...",0.706776,65.638634,0.706776

# Регрессии

In [14]:
import pandas as pd
names = ['lin_reg_l1.csv', 'lin_reg_l2.csv', 'rf_reg.csv',
         'svmreg_results.csv', 'catboost_reg_results.csv']
# df = pd.read_csv
def get_df(name):
    df = pd.read_csv(name)
    df['method'] = name.split('.')[0]
    return df.sample(10)
dfs = [get_df(name) for name in names]

In [15]:
combined_metrics = pd.concat(dfs, axis=0)
combined_metrics

,Unnamed: 0,number,value,datetime_start,datetime_complete,duration,params_model__alpha,params_model__tol,state,method,...,params_model__min_samples_split,params_model__n_estimators,params_regressor__C,params_regressor__max_iter,params_regressor__tol,params_depth,params_early_stopping_rounds,params_iterations,params_l2_leaf_reg,params_learning_rate
4,4,4,-23.008521,2026-06-16 21:28:57.949860,2026-06-16 21:29:29.723855,0 days 00:00:31.773995,0.031900,2.500811e-06,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,-23.011680,2026-06-16 21:28:26.329912,2026-06-16 21:28:53.568834,0 days 00:00:27.238922,0.035855,1.994900e-05,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,6,-23.004283,2026-06-16 21:30:15.905036,2026-06-16 21:31:06.516052,0 days 00:00:50.611016,0.003573,6.405962e-07,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,5,-23.005252,2026-06-16 21:29:29.727756,2026-06-16 21:30:15.901980,0 days 00:00:46.174224,0.016630,2.853396e-07,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,-25.895455,2026-06-16 21:28:22.756614,2026-06-16 21:28:26.326460,0 days 00:00:03.569846,0.689769,4.628644e-05,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,-23.015084,2026-06-16 21:31:06.519035,2026-06-16 21:31:34.045731,0 days 00:00:27.526696,0.039460,5.773953e-08,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,-25.978483,2026-06-16 21:28:53.574088,2026-06-16 21:28:57.946287,0 days 00:00:04.372199,0.710037,6.234173e-07,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0,-23.106705,2026-06-16 21:28:05.674904,2026-06-16 21:28:22.753851,0 days 00:00:17.078947,0.095202,9.252828e-06,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,8,-23.005383,2026-06-16 21:31:34.048786,2026-06-16 21:32:23.576093,0 days 00:00:49.527307,0.005513,2.657290e-07,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,9,-23.004782,2026-06-16 21:32:23.578916,2026-06-16 21:33:13.094915,0 days 00:00:49.515999,0.006287,2.914425e-07,COMPLETE,lin_reg_l1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,-22.992045,2026-06-16 21:34:28.123994,2026-06-16 21:34:30.341896,0 days 00:00:02.217902,0.250475,1.897746e-06,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,-22.991668,2026-06-16 21:34:40.571070,2026-06-16 21:34:42.814129,0 days 00:00:02.243059,0.001078,1.105869e-05,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,5,-22.991620,2026-06-16 21:34:34.929586,2026-06-16 21:34:37.261170,0 days 00:00:02.331584,0.002892,7.201681e-06,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,-22.991525,2026-06-16 21:34:32.651682,2026-06-16 21:34:34.926036,0 days 00:00:02.274354,0.008062,3.420328e-05,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,9,-22.991584,2026-06-16 21:34:45.086759,2026-06-16 21:34:47.332427,0 days 00:00:02.245668,0.004543,4.296333e-07,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,6,-22.991412,2026-06-16 21:34:37.265902,2026-06-16 21:34:40.567033,0 days 00:00:03.301131,0.021091,4.036193e-05,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,-22.991776,2026-06-16 21:34:30.346041,2026-06-16 21:34:32.647710,0 days 00:00:02.301669,0.150351,2.897242e-06,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,8,-22.991429,2026-06-16 21:34:42.817076,2026-06-16 21:34:45.084422,0 days 00:00:02.267346,0.018124,4.048312e-05,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,-22.991562,2026-06-16 21:34:25.516302,2026-06-16 21:34:28.120210,0 days 00:00:02.603908,0.073380,6.321009e-08,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0,-22.991464,2026-06-16 21:34:22.418098,2026-06-16 21:34:25.511036,0 days 00:00:03.092938,0.047081,6.313563e-07,COMPLETE,lin_reg_l2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,-27.739030,2026-06-16 22:37:29.010660,2026-06-16 22:38:10.878355,0 days 00:00:41.867695,NaN,NaN,COMPLETE,rf_reg,...,20.0,290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,8,-20.053618,2026-06-16 22:37:34.149151,2026-06-16 22:38:02.684138,0 days 00:00:28.534987,NaN,NaN,COMPLETE,rf_reg,...,2.0,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,-16.535493,2026-06-16 22:34:06.838483,2026-06-16 22:35:18.780432,0 days 00:01:11.941949,NaN,NaN,COMPLETE,rf_reg,...,4.0,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,6,-35.591983,2026-06-16 22:37:22.058883,2026-06-16 22:37:28.999165,0 days 00:00:06.940282,NaN,NaN,COMPLETE,rf_reg,...,5.0,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,-14.162252,2026-06-16 22:34:06.183417,2026-06-16 22:35:41.738913,0 days 00:01:35.555496,NaN,NaN,COMPLETE,rf_reg,...,14.0,290.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,0,0,-22.558060,2026-06-16 22:33:30.397906,2026-06-16 22:34:06.829816,0 days 00:00:36.431910,NaN,NaN,COMPLETE,rf_reg,...,8.0,230.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,9,-25.074201,2026-06-16 22:38:02.694559,2026-06-16 22:38:29.309278,0 days 00:00:26.614719,NaN,NaN,COMPLETE,rf_reg,...,8.0,410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,-13.858639,2026-06-16 22:35:18.793732,2026-06-16 22:37:34.136126,0 days 00:02:15.342394,NaN,NaN,COMPLETE,rf_reg,...,4.0,410.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,5,-22.222790,2026-06-16 22:35:41.757810,2026-06-16 22:37:22.050117,0 days 00:01:40.292307,NaN,NaN,COMPLETE,rf_reg,...,4.0,470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,-22.437112,2026-06-16 22:33:30.411930,2026-06-16 22:34:06.166165,0 days 00:00:35.754235,NaN,NaN,COMPLETE,rf_reg,...,9.0,470.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,7,-22.290122,2026-06-16 19:39:51.289024,2026-06-16 19:39:53.183124,0 days 00:00:01.894100,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.224756,1000.0,0.000410,NaN,NaN,NaN,NaN,NaN
1,1,1,-22.985212,2026-06-16 19:37:58.432134,2026-06-16 19:37:59.716511,0 days 00:00:01.284377,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.049142,9000.0,0.006171,NaN,NaN,NaN,NaN,NaN
8,8,8,-25.848523,2026-06-16 19:39:53.186276,2026-06-16 19:39:55.044483,0 days 00:00:01.858207,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.007324,9000.0,0.000243,NaN,NaN,NaN,NaN,NaN
9,9,9,-41.777294,2026-06-16 19:39:55.046311,2026-06-16 19:39:56.399020,0 days 00:00:01.352709,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.000463,9000.0,0.000076,NaN,NaN,NaN,NaN,NaN
4,4,4,-22.084272,2026-06-16 19:38:02.450897,2026-06-16 19:39:29.056015,0 days 00:01:26.605118,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,11.727428,5000.0,0.000025,NaN,NaN,NaN,NaN,NaN
0,0,0,-22.253472,2026-06-16 19:37:51.778399,2026-06-16 19:37:58.429976,0 days 00:00:06.651577,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.263501,8000.0,0.000213,NaN,NaN,NaN,NaN,NaN
6,6,6,-22.092172,2026-06-16 19:39:30.893106,2026-06-16 19:39:51.287114,0 days 00:00:20.394008,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,2.522947,7000.0,0.000018,NaN,NaN,NaN,NaN,NaN
5,5,5,-22.534360,2026-06-16 19:39:29.059173,2026-06-16 19:39:30.890287,0 days 00:00:01.831114,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.108606,6000.0,0.002883,NaN,NaN,NaN,NaN,NaN
2,2,2,-24.153726,2026-06-16 19:37:59.718306,2026-06-16 19:38:01.194297,0 days 00:00:01.475991,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.016069,1000.0,0.000027,NaN,NaN,NaN,NaN,NaN
3,3,3,-24.783654,2026-06-16 19:38:01.196477,2026-06-16 19:38:02.448237,0 days 00:00:01.251760,NaN,NaN,COMPLETE,svmreg_results,...,NaN,NaN,0.011313,4000.0,0.003218,NaN,NaN,NaN,NaN,NaN
9,9,9,-12.708815,2026-06-16 20:16:52.446290,2026-06-16 20:21:39.220985,0 days 00:04:46.774695,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,6.0,10.0,800.0,0.640179,0.046761
7,7,7,-13.047618,2026-06-16 20:14:21.635837,2026-06-16 20:15:48.994621,0 days 00:01:27.358784,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,5.0,100.0,300.0,0.234138,0.141579
5,5,5,-13.926051,2026-06-16 20:09:03.412469,2026-06-16 20:10:01.865811,0 days 00:00:58.453342,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,5.0,80.0,200.0,0.232020,0.099942
8,8,8,-15.502012,2026-06-16 20:15:48.998225,2026-06-16 20:16:52.444147,0 days 00:01:03.445922,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,4.0,65.0,300.0,0.018896,0.042637
3,3,3,-12.921639,2026-06-16 20:03:31.759650,2026-06-16 20:06:46.093807,0 days 00:03:14.334157,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,4.0,90.0,900.0,9.924445,0.165051
1,1,1,-13.830133,2026-06-16 19:58:50.378955,2026-06-16 20:02:09.181769,0 days 00:03:18.802814,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,4.0,90.0,900.0,0.104016,0.040603
2,2,2,-15.281680,2026-06-16 20:02:09.184464,2026-06-16 20:03:31.757519,0 days 00:01:22.573055,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,5.0,70.0,300.0,4.379905,0.033503
4,4,4,-13.070482,2026-06-16 20:06:46.097386,2026-06-16 20:09:03.408682,0 days 00:02:17.311296,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,4.0,100.0,600.0,0.172059,0.134080
0,0,0,-13.432549,2026-06-16 19:56:57.364999,2026-06-16 19:58:50.376435,0 days 00:01:53.011436,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,4.0,55.0,500.0,0.055008,0.106274
6,6,6,-13.398525,2026-06-16 20:10:01.868268,2026-06-16 20:14:21.632895,0 days 00:04:19.764627,NaN,NaN,COMPLETE,catboost_reg_results,...,NaN,NaN,NaN,NaN,NaN,5.0,20.0,900.0,0.077243,0.032969

In [17]:

# Сортируем данные по времени старта
df_sorted = combined_metrics.sort_values('datetime_start').reset_index(drop=True)

# Добавляем колонку-порядковый номер (ось X)
df_sorted['order'] = df_sorted.index + 1  # чтобы начиналось с 1
df_sorted['value'] *= -1
# Строим точечный график без линий
fig = px.scatter(
    df_sorted,
    x='order',
    y='value',
    color='method',
    title='MAE-score Кросс-Валидация на 5 фолдах',
    labels={
        'order': 'Номер эксперимента',
        'value': 'MAE',
        'method': 'Метод'
    }
)

fig.update_traces(marker=dict(size=18))

fig.show()